"""Update table stats

Revision ID: 87b0730120b9
Revises: a00095606808
Create Date: 2026-04-07 14:42:32.737223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87b0730120b9'
down_revision: Union[str, Sequence[str], None] = 'a00095606808'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stats', 'total_spend',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stats', 'total_spend',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.BIGINT(),
               existing_nullable=False)
    # ### end Alembic commands ###
