"""Update table orders

Revision ID: a00095606808
Revises: 34c28fd91388
Create Date: 2026-04-05 22:07:56.675488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a00095606808'
down_revision: Union[str, Sequence[str], None] = '34c28fd91388'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('update_cooldown', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'update_cooldown')
    # ### end Alembic commands ###
